### ISSUE TITLE
抱歉，未找到 Web Font URL 或引用方法，还望不吝指教。

### ISSUE THREAD

**Issue by cnyyk** [jeffreyxuan/toneoz-font-pinyin-wenkai#20]
感谢您在此项目的卓著贡献，善莫大焉。

在此处 https://toneoz.com/blog/2021/09/08/wenkai-font/ 有提及特色之一：```免费商用、可支持Web Font免安装```，但一直未找到 web font 的引用地址。

有看到您网站的 Web Font 字体引用，但未在 Github / NPM / jsDelivr 上找到对应的公开可引用的 URL。

烦请指教上述 Web Font 如何使用，或分享对应资源。

再次感谢！

**Comment by jeffreyxuan** [comment]
@cnyyk 您好, 

目前此开源项目(toneoz-font-pinyin-wenkai)并没有提供Web Font引用喔! 

关于您看到的blog, 该章节介绍的是另一个软件(免费在线多音字编辑器https://toneoz.com/ime), 该编辑器"支持Web Font"指的是"不用在本机安装字型", 该编辑器会自动使用专属的Web Font. 

本项目字型提供免费商用, 但是提供引用的伺服器"Bandwidth带宽"是需要经费支持的, 欢迎透过斗内捐款赞助我们 (https://github.com/jeffreyxuan/toneoz-font-pinyin-wenkai/blob/master/README.md#donate-%E8%AB%8B%E6%96%97%E5%85%A7%E6%8D%90%E6%AC%BE%E6%94%AF%E6%8C%81%E6%88%91%E5%80%91), 伺服器所需经费约每年美金$100, 如果有两年经费我们就能实现Web Font引用:)

**Comment by cnyyk** [comment]
感谢回复。暂时先关闭。
