### ISSUE TITLE
adv3重編本國語辭典字音ivs缺音 : 花刺子模

### ISSUE THREAD

**Issue by jeffreyxuan** [jeffreyxuan/toneoz-font-pinyin-wenkai#28]
曉聲通辭典字音掃描, adv3重編本國語辭典, 以下字詞字音ivs缺音

弄刺子兒 nòng là zǐ ēr <= 花刺子模
忠言奇謀 zhōng yán qí mó _____________________________ 谋
懸絲傀儡 xuán sī kuí lěi
截蒲為牒 jié pǔ wéi dié
打了個千兒 dǎ le ge qiā ēr
打了個盹兒 dǎ le ge  ēr  <= 盹ㄉㄨㄜˇ <= 注音規則缺音
打幌 dǎ huàng
打攙 dǎ chán ____________________________________________ 搀
掙䦟 zhèng chuài
插扛子 chā gàng zi
插火坑 chā huǒ kàng
擺弄 bǎi nōng  <= 弄ㄋㄨㄥ         <= 注音規則缺音
格格 gē gē
榆瞑豆重 yú mián dòu zhòng
毛廁 máo si ___________________________________________ 厕
毛廁裡磚兒 máo si lǐ zhuān ēr _________________________ 厕
氆氌 pǔ lū
汀濘 tīng níng ________________________________________ 泞
沒掂三 méi diàn sān
沒搭撒 méi dā sà
洛謨尼 luò mò ní ______________________________________ 谟
燒火焜 shāo huǒ gùn
玍古 gǎ gu <= 相聲段子

**Comment by lxgw** [comment]
「花刺子模」的「刺」是否为错字？正确的应该是「花剌子模」。

**Comment by jeffreyxuan** [comment]
感謝提醒，「刺」確實是個錯字。這個 issue #28 是使用程式核對台灣教育部「重編本辭典」的讀音。該辭典是上世紀台灣教育界的專家學者所編輯,年代在1976年左右,我才剛出生...。其中有個條目「弄刺子兒 nòng là zǐ ēr 」紀錄出處是《金瓶梅(1610年)》第二二回：「....諕鬼弄刺子兒...」

嚴謹來說，明朝民間的章回小說錯字頗多，「刺」「剌」兩字字形太接近，很有可能是金瓶梅某版本的刻板錯了。issue #28提及錯字寫法「花刺子模」是小弟為了參考加上的註解。

正確寫法的「花剌子模」這個條目在重編本中是使用正確的「剌」沒錯：
[https://toneoz.com/imez/?dq=%E8%8A%B1%E5%89%8C%E5%AD%90%E6%A8%A1&dy=hu%C4%81_l%C3%A0_z%C7%90_m%C3%B3&fnt=9](url)

 issue #28 是因為小弟最近弄在線國語辭典，希望能讓所有的詞條能有相對應的拼音注音字型。該錯誤唸法「刺là」歷史400年，編入辭典超過40年，目前的規劃是「字型」仍然實作這個音，用法對錯則交由「字典」工具來協助。

**Comment by jeffreyxuan** [comment]
另外參見重編本詞條「胡遮刺 hú zhē là」元．鄭廷玉《後庭花》第三折：「須不是把你來胡遮刺，莫不我雙眼昏花。」
