### ISSUE TITLE
IVS缺音: 洋涇「濱 bāng」

### ISSUE THREAD

**Issue by jeffreyxuan** [jeffreyxuan/toneoz-font-pinyin-wenkai#30]
國語重編本辭典「濱」:
此字於吳語中音ㄅㄤ，如：「洋涇濱」

**Comment by ButTaiwan** [comment]
一字多音審訂表列單音字

![image](https://user-images.githubusercontent.com/5418570/217692340-3138753e-738b-4d3a-b381-e0d7a2f0b5e0.png)
