### ISSUE TITLE
新華字典校音,IVS缺音 : ⺆ jiōng

### ISSUE THREAD

**Issue by jeffreyxuan** [jeffreyxuan/toneoz-font-pinyin-wenkai#31]
⺆ jiōng
「新華字典12版」用甩的部首為「⺆」, 此字查不到發音,但「⺆」通「冂 jiōng」,即「用yòng」部

**Comment by ButTaiwan** [comment]
⺆ U+2E86 是康熙字典部首區的非漢字。
冂 U+5182 是漢字。
為了避免麻煩，我記得我有刻意一律不收康熙字典部首區的字。

**Comment by jeffreyxuan** [comment]
fixed in release 0.230212
保留 ⺆ U+2E86 混亂字型(全字庫楷體的部首偏旁區使用了宋體來做區別, 澳聲通庫楷 release 0.230212 則改用霞霧文楷來做區別)
加上拼音 jiōng , 放便老師課堂上介紹部首時唸讀使用。
