### ISSUE TITLE
新聞字詞IVS缺音 : 諶 shèn

### ISSUE THREAD

**Issue by jeffreyxuan** [jeffreyxuan/toneoz-font-pinyin-wenkai#33]
https://news.tvbs.com.tw/life/38917?fbclid=IwAR2hbLSL52l8F7gtmRFU3mjeQewd97u4f4ho5MXFMl-hZFbLDMHn9RL3EkE
新北市有兩位局處首長，明明同一個姓氏，但1位是「ㄔㄣˊ」處長，一位是「ㄕㄣˋ」副局長，究竟怎麼回事？原來他們的姓是一個言字邊加上甚至的「甚」，教育部字典唸「ㄔㄣˊ 」，但根據族譜追溯這個姓氏最早出現在河南，大陸200多萬人都念「ㄕㄣˋ」

**Comment by ButTaiwan** [comment]
一字多音審訂表...XD

![image](https://user-images.githubusercontent.com/5418570/217692974-8cca7917-86d6-46a5-b0e4-b1827c4771c6.png)

姓氏還真是麻煩。

**Comment by jeffreyxuan** [comment]
fixed in release 0.230212
