### ISSUE TITLE
「闕」拼音錯誤，「que2」應爲「jue2」

### ISSUE THREAD

**Issue by 86xiang** [jeffreyxuan/toneoz-font-pinyin-wenkai#44]
目前「闕」標註的拼音有「que4」「que1」「que2」。
其中「que2」應爲「jue2」。

《辭源》如下：
> 1. què ㄑㄩㄝˋ 去月切，入，月韻，溪。月部。
> ㊀古代宮廟及墓門立雙柱者謂之闕，其上連有飛檐罘罳者謂之連闕。
> 左傳莊二一年：“鄭伯享王于闕西辟。”
> 也稱象魏。參閲晉崔豹古今注上都邑。
> ㊁城樓。見“城闕㊀”。
> ㊂指皇帝所居。
> 漢書六四上朱買臣傳：“詣闕上書，書久不報。”

> 2. quē ㄑㄩㄝ 去月切，入，月韻，溪。月部。
> ㊀過失。
> 詩大雅烝民：“袞職有闕，維仲山甫補之。”
> 左傳襄四年：“昔周辛甲之爲大史也，命百官，官箴王闕。”
> ㊁空，空闕。
> 左傳昭二十年：“使華寅肉袒執蓋，以當其闕。”
> 論語子路：“君子於其所不知，蓋闕如也。”
> 宋史選舉志四銓法上：“紹定元年，臣僚上言：‘銓曹之患，員多闕少，注擬甚難。’”
> ㊂缺少，短缺。
> 國語魯下：“若盟而棄魯侯，信抑闕矣。”
> ㊃姓。後漢書獻帝紀有闕宣。

> 3. jué ㄐㄩㄝˊ 集韻其月切，入，月韻，羣。月部。
> ㊀毁傷。
> 呂氏春秋孝行：“父母置之，子弗敢廢。父母全之，子弗敢闕。”
> ㊁通“掘”。
> 左傳隱元年：“若闕地及泉，隧而相見，其誰曰不然。”

參考資料：
1. 字統網：https://zi.tools/zi/%E9%97%95
2. 漢語大字典：https://homeinmists.ilotus.org/hd/hydzd3.php?st=page_no&kw=4391
3. 維基詞典：https://zh.wiktionary.org/wiki/%E9%97%95

**Comment by jeffreyxuan** [comment]
@86xiang  感謝提醒,確實是缺音, 下一個版本會加以修正.

**Comment by jeffreyxuan** [comment]
v0.240331 讀音已更新, 「闕」標註的拼音有「que4」「que1」「que2」
