### ISSUE TITLE
麻烦更新一下《霞鹜文楷 GB》，多谢了！

### ISSUE THREAD

**Issue by pkj-l** [jeffreyxuan/toneoz-font-pinyin-wenkai#45]
旧版《霞鹜文楷 GB 融合》里头[部分字形用了仓耳今楷进行 zi2zi（一种 AI 生成字形工具），有版权顾虑](https://github.com/lxgw/LxgwWenKai/issues/128)。
请更新到《霞鹜文楷 GB 融合》[v1.015](https://github.com/lxgw/LxgwWenkaiGB-Fusion/releases/tag/v1.015)，该版本使用思源宋体 zi2zi 重新生成了字形，无版权顾虑。
**多谢！**

**Comment by jeffreyxuan** [comment]
感謝信息! 近期會找時間更新霞鹜文楷 GB母字型到最新版。

**Comment by jeffreyxuan** [comment]
v0.240331 更新霞鹜文楷 GB母字型到最新版。
