### ISSUE TITLE
Can you provide a guide to build the fonts?

### ISSUE THREAD

**Issue by catusf** [jeffreyxuan/toneoz-font-pinyin-wenkai#46]
It would be great if you can provide a guide for us to update and build the fonts.

**Comment by jeffreyxuan** [comment]
@catusf 
For the detail of how to update and build the fonts, please refer to here :
https://github.com/MaruTama/Mengshen-pinyin-font/blob/master/doc/HOW_TO_MAKE_EN.md

toneoz-font-pinyin-wenkai is based on Mengshen-pinyin-font
